apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ip-viewer-app
spec:
  replicas: 8
  selector:
    matchLabels:
      app: ip-app
  template:
    metadata:
      labels:
        app: ip-app
    spec:
      containers:
        - name: ip-app
          image: dipakrasal2009/ip-view:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-ip-app1
spec:
  type: NodePort
  selector:
    app: ip-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # You can change this if nee
